import UserTemplat from "@/components/userTamplate";
import ProductList from "../productList";

export const metadata = {
  title: "Order Product | Eco Market",
  description: "Generated by create next app",
};

type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <UserTemplat
      title="Order Product"
      id="order_product"
      productList={ProductList}
    >
      {children}
    </UserTemplat>
  );
};
export default RootLayout;
