import UserTemplate from "@/components/userTamplate";
import ProductList from "../productList";

export const metadata = {
  title: "Dashboard | Eco Market",
  description: "Generated by create next app",
};

type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <UserTemplate title="Dashboard" id="dashboard" productList={ProductList}>
      {children}
    </UserTemplate>
  );
};
export default RootLayout;
