import UserTemplate from "@/components/userTamplate";
import ProductList from "../productList";

export const metadata = {
  title: "Transaksi | Eco Market",
  description: "Generated by create next app",
};

type PropsLayout = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: PropsLayout) => {
  return (
    <UserTemplate title="Transaksi" id="Transaksi" productList={ProductList}>
      {children}
    </UserTemplate>
  );
};

export default RootLayout;
