import ManagerTemplate from "@/components/adminTemplate";
import MenuList from "../productList";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "User | Eco Market",
  description: "Generated by create next app",
};
type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <ManagerTemplate title="User" id="User" productList={MenuList}>
      {children}
      <ToastContainer containerId={`toastUser`} />
    </ManagerTemplate>
  );
};
export default RootLayout;
