import ManagerTemplate from "@/components/adminTemplate";
import MenuList from "../productList";
export const metadata = {
  title: "Transaksi | Ordering System",
  description: "Generated by create next app",
};
type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <ManagerTemplate title="Transaksi" id="Transaski" productList={MenuList}>
      {children}
    </ManagerTemplate>
  );
};
export default RootLayout;
