import ManagerTemplate from "@/components/adminTemplate";
import ProductList from "../productList";
export const metadata = {
  title: "Dashboard | Ordering System",
  description: "Generated by create next app",
};
type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <ManagerTemplate title="Dashboard" id="dashboard" productList={ProductList}>
      {children}
    </ManagerTemplate>
  );
};
export default RootLayout;
