import UserTemplate from "@/components/userTamplate";
import ProductList from "../productList";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Product | Eco Market",
  description: "Generated by create next app",
};

type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <UserTemplate title="Product" id="Product" productList={ProductList}>
      {children}
      <ToastContainer containerId={`toastMenu`} />
    </UserTemplate>
  );
};
export default RootLayout;
