import UserTemplate from "@/components/userTamplate";
import ProductList from "../productList";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Product_favorite | Eco Market",
  description: "Generated by create next app",
};

type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <UserTemplate
      title="Product favorite"
      id="product_favorite"
      productList={ProductList}
    >
      {children}
      <ToastContainer containerId={`toastUser`} />
    </UserTemplate>
  );
};
export default RootLayout;
